language: ruby

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - witowski.sebastian@gmail.com
    on_failure: change
    on_success: never